kind: Deployment
apiVersion: apps/v1
metadata:
  name: jobs-service
  namespace: {{ .Values.orchestrator.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-service
  template:
    metadata:
      labels:
        app: jobs-service
    spec:
      containers:
      - name: jobs-service
        image: {{ .Values.orchestrator.jobsservice.image }}
# https://access.redhat.com/solutions/7002730
{{- if eq (include "is-openshift" .) "true" }}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
{{- end }}        
        ports:
        - containerPort: 8080
        env:
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: "{{- include "get-postgres-jdbc-url" . }}?currentSchema=jobs-service"
        - name: QUARKUS_DATASOURCE_REACTIVE_URL
          value: "{{- include "get-postgres-reactive-url" . }}?search_path=jobs-service"
        - name: JOBS_SERVICE_PERSISTENCE
          value: postgresql
        - name: QUARKUS_DATASOURCE_DB_KIND
          value: postgresql
        - name: QUARKUS_DATASOURCE_USERNAME
          value: {{ .Values.postgres.username }}
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: '{{- include "get-postgres-secret-name" . }}'
              key: {{ .Values.postgres.secretKeys.userPasswordKey }}
        - name: KOGITO_JOBS_SERVICE_KNATIVE_EVENTS
          value: "false"
        - name: SCRIPT_DEBUG
          value: "false"
        - name: QUARKUS_LOG_LEVEL
          value: INFO
      initContainers:
        - name: init-postgres
          image: busybox:1.36
# https://access.redhat.com/solutions/7002730
{{- if eq (include "is-openshift" .) "true" }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
{{- end }}        
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -vz {{ include "get-postgres-host" . }}:{{ .Values.postgres.port }}; do echo "Waiting for postgres server"; sleep 3; done;']
--- 
kind: Service
apiVersion: v1
metadata:
  name: jobs-service-service
  namespace: {{ .Values.orchestrator.namespace }}
  labels: 
      app: jobs-service
spec:
  selector:
    app: jobs-service
  ports:
    - protocol: TCP
      port: {{ .Values.orchestrator.jobsservice.port }}
      targetPort: {{ .Values.orchestrator.jobsservice.port }}