{{- if eq "true" (include "install-tekton-pipeline" .) }}
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: workflow-deployment
  namespace: {{ .Values.orchestrator.namespace }}
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
    - name: gitUrl
      description: The SSH URL of the repository to clone
      type: string
    - name: gitConfigUrl
      description: The SSH URL of the config repository for pushing the changes
      type: string
    - name: workflowId
      description: The workflow ID from the repository
      type: string
    - name: convertToFlat
      description: Whether conversion to flat layout is needed or it's already flattened
      type: string
      default: "true"
  workspaces:
    - name: workflow-source
    - name: workflow-config
    - name: ssh-creds
    - name: docker-credentials
  tasks:
    - name: fetch-workflow
      taskRef:
        name: git-cli
      workspaces:
        - name: source
          workspace: workflow-source
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: GIT_USER_NAME
          value: Parodos Tekton Pipeline
        - name: GIT_USER_EMAIL
          value: parodos@redhat.com
        - name: USER_HOME
          value: /home/git
        - name: GIT_SCRIPT
          value: |
            eval "$(ssh-agent -s)"
            ssh-add "${PARAM_USER_HOME}"/.ssh/id_rsa
            git clone $(params.gitUrl) workflow
            cd workflow
    - name: fetch-workflow-config
      taskRef:
        name: git-cli
      workspaces:
        - name: source
          workspace: workflow-config
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: GIT_USER_NAME
          value: Parodos Tekton Pipeline
        - name: GIT_USER_EMAIL
          value: parodos@redhat.com
        - name: USER_HOME
          value: /home/git
        - name: GIT_SCRIPT
          value: |
            eval "$(ssh-agent -s)"
            ssh-add "${PARAM_USER_HOME}"/.ssh/id_rsa
            git clone $(params.gitConfigUrl) workflow-config
    - name: flatten-workflow
      runAfter: ["fetch-workflow"]
      taskRef:
        name: flattener
      workspaces:
        - name: workflow-source
          workspace: workflow-source
      params:
        - name: workflowId
          value: $(params.workflowId)
        - name: convertToFlat
          value: $(params.convertToFlat)
    - name: build-manifests
      runAfter: ["flatten-workflow"]
      taskRef:
        name: build-manifests
      workspaces:
        - name: workflow-source
          workspace: workflow-source
      params:
        - name: workflowId
          value: $(params.workflowId)
    - name: build-config
      runAfter: ["build-manifests", "fetch-workflow-config"]
      taskRef:
        name: build-config
      workspaces:
        - name: workflow-source
          workspace: workflow-source
        - name: workflow-config
          workspace: workflow-config
      params:
        - name: workflowId
          value: $(params.workflowId)
        - name: imageTag
          value: $(tasks.fetch-workflow.results.commit)
    - name: build-and-push-image
      runAfter: ["flatten-workflow"]
      taskRef:
        name: buildah
        kind: ClusterTask        
      workspaces:
        - name: source
          workspace: workflow-source
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: quay.io/orchestrator/serverless-workflow-$(params.workflowId):$(tasks.fetch-workflow.results.commit)
        - name: DOCKERFILE
          value: flat/workflow-builder.Dockerfile
        - name: CONTEXT
          value: flat/$(params.workflowId)
        - name: BUILD_EXTRA_ARGS
          value: --ulimit nofile=4096:4096             
    - name: push-workflow-config
      runAfter: ["build-config", "build-and-push-image"]
      taskRef:
        name: git-cli
      workspaces:
        - name: source
          workspace: workflow-config
        - name: ssh-directory
          workspace: ssh-creds
      params:
        - name: GIT_USER_NAME
          value: Parodos Tekton Pipeline
        - name: GIT_USER_EMAIL
          value: parodos@redhat.com
        - name: USER_HOME
          value: /home/git
        - name: GIT_SCRIPT
          value: |
            WORKFLOW_COMMIT=$(tasks.fetch-workflow.results.commit)

            eval "$(ssh-agent -s)"
            ssh-add "${PARAM_USER_HOME}"/.ssh/id_rsa

            cd workflow-config
            git add .
            git diff
            # TODO: create PR
            git commit -m "Deployment for workflow commit $WORKFLOW_COMMIT from $(params.gitUrl)"
            # TODO: parametrize branch
            git push origin main
{{- end }}