apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: workflow-orchestrator-entities
  description: A collection of Backstage entities for Workflow orchestrator
spec:
  type: url
  targets:
    - https://github.com/parodos-dev/workflow-software-templates/tree/main/entities/system.yaml
    - https://github.com/parodos-dev/workflow-software-templates/tree/main/entities/group.yaml
