apiVersion: v1
data:
  application.properties: |2-

    # Configuration for the incoming cloud events received by the serverless workflows.
    mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
    mp.messaging.incoming.kogito_incoming_stream.path=/
    mp.messaging.incoming.kogito_incoming_stream.method=POST


    move2kube_url={{ .Values.workflow.move2kubeURL }}
    quarkus.rest-client.move2kube_yaml.url={{ .Values.workflow.move2kubeURL }}
    broker_url={{ .Values.workflow.brokerURL }}
    quarkus.rest-client.notifications_yaml.url={{ .Values.workflow.backstageNotificationURL }}
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.workflow.name }}
    sonataflow.org/workflow-app: {{ .Values.workflow.name }}
  name: {{ .Values.workflow.name }}-props
  namespace: {{ .Values.namespace }}
