apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: error-trigger-{{ .Values.workflow.name }}
  namespace: {{ .Values.namespace }}
spec:
  broker: {{ .Values.brokerName }}
  filter:
    attributes:
      type: error
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: {{ .Values.workflow.name }}
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: transformation-saved-trigger-{{ .Values.workflow.name }}
  namespace: {{ .Values.namespace }}
spec:
  broker: {{ .Values.brokerName }}
  filter:
    attributes:
      type: transformation_saved
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: {{ .Values.workflow.name }}
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: {{ .Values.brokerName }}
  namespace: {{ .Values.namespace }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.kfunction.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      name: {{ .Values.kfunction.name }}-v1
    spec:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
          securityContext:
          command: [ "sh", "-c", "cp /tmp/.ssh/id_rsa /etc/pre-install/. && chown 185 /etc/pre-install/id_rsa" ]
          volumeMounts:
            - name: ssh-priv-key
              mountPath: "/tmp/.ssh/id_rsa"
              subPath: id_rsa
              readOnly: true
            - name: pre-install
              mountPath: /etc/pre-install
      containers:
        - image: {{ .Values.kfunction.image }}
          imagePullPolicy: Always
          env:
            - name: EXPORTED_FUNC
              value: saveTransformation
            - name: SSH_PRIV_KEY_PATH
              value: /home/jboss/.ssh/id_rsa
            - name: BROKER_URL
              value: {{ .Values.workflow.brokerURL }}
            - name: MOVE2KUBE_API
              value: {{ .Values.workflow.move2kubeURL }}/api/v1
          name: user-container
          volumeMounts:
            - name: pre-install
              readOnly: true
              mountPath: "/home/jboss/.ssh/id_rsa"
              subPath: id_rsa
            - name: ssh-pub-key
              readOnly: true
              mountPath: "/home/jboss/.ssh/id_rsa.pub"
              subPath: id_rsa.pub

          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
      volumes:
        - name: ssh-priv-key
          secret:
            secretName: {{ .Values.sshSecretName }}
            defaultMode: 384
        - name: ssh-pub-key
          secret:
            secretName: {{ .Values.sshSecretName }}
        - name: pre-install
          emptyDir: { }

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: m2k-save-transformation-event
  namespace: {{ .Values.namespace }}
spec:
  broker: {{ .Values.brokerName }}
  filter:
    attributes:
      type: save-transformation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: {{ .Values.kfunction.name }}
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: {{ .Values.workflow.name }}-sb
  namespace: {{ .Values.namespace }}
spec:
  subject:
    apiVersion: v1/apps
    kind: Deployment
    selector:
      matchLabels:
        app: {{ .Values.workflow.name }}
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: {{ .Values.brokerName }}
      namespace: {{ .Values.namespace }}