name: PR notice
on:
  pull_request:
    types:
      - opened
    paths:
      - "chart/orchestrator/"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat << EOF | gh pr comment ${{ github.event.number }} -F -
          ðŸ“¢ Repository Notice
          This repository is now dedicated to maintaining the stable-1.1.x version of the Orchestrator, which is deployed using a Helm chart.
          
          âš ï¸ Important: The installation method for Orchestrator 1.2.x has been changed to be operator-based.
          Development for this version now happens in the Orchestrator Helm Operator repository.
             
          Additionally, this repository will continue to be the home for developing the orchestrator-k8s Helm chart.
          
          If this change includes changes to the orchestrator helm chart, please
          close the PR and send it to https://rhdhorchestrator/orchestrator-helm-operator instead"
          EOF
        
